version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - "static_volume:/home/app/web/staticfiles"
    depends_on:
      - web

  web:
    build: .
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - "static_volume:/home/app/staticfiles"
    depends_on:
      - cache
      - db

  cache:
    image: "memcached:alpine"
    ports:
      - "8002:11211"
    command:
      - '--memory-limit=128'
    depends_on:
      - db

  db:
    image: "postgres:15.0-alpine"
    ports:
      - "8001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  postgres_data:
  static_volume:
