version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - "static_volume:/home/app/web/staticfiles"
      - "media_volume:/home/app/web/mediafiles"
    depends_on:
      - web

  web:
    build: .
    expose:
      - ${PORT}
    env_file:
      - ./.env.prod
    volumes:
      - "static_volume:/app/staticfiles"
      - "media_volume:/app/media"
    depends_on:
      - cache
      - db

  cache:
    image: "redis:7.0-alpine"
    expose:
      - "6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - cache_volume:/data
    depends_on:
      - db

  db:
    image: "postgres:15.0-alpine"
    expose:
      - "5432"
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  db_volume:
  cache_volume:
  static_volume:
  media_volume:
